config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :tasks
  resources :users

  resources :users
    resources :projects do
      resources :tasks do
        resources :comments
      end
    end

    resources :projects do
      resources :memberships
  end

  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
  get '/signin' => 'authentications#new'
  post '/signin' => 'authentications#create'
  get '/signout' => 'authentications#destroy'

get '/' => 'welcome#index'

get '/faq' => 'common_questions#index'

get '/about' => 'about#index'

get '/terms' => 'terms#index'

get '/tasks' => 'tasks#index'




end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :project
  belongs_to :user

  enum role: {member: 0, owner: 1}

  validates :user_id, presence: true, uniqueness: {scope: :project_id, message: "has already been added to this project."}

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate
  before_action :set_project

  def index
    @project = Project.find(params[:project_id])
    @memberships = @project.memberships.all
    @membership = Membership.new
  end

  def show
    @project = Project.find(params[:project_id])
    @membership = @project.memberships.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @membership = Membership.new
  end

  def create
    @project = Project.find(params[:project_id])
    @membership = Membership.new(membership_params)
    @membership.project_id = @project.id
    if @membership.save
      redirect_to project_memberships_path(@project),  notice: "#{@membership.user.full_name} was succesfully added!"
    else
      render :index
    end
  end


  def update
    @project = Project.find(params[:project_id])
    @membership = Membership.find(params[:id])
    if @membership.role == "owner" && @project.memberships.where(role: 1).count == 1
      redirect_to project_memberships_path(@project), alert: "Projects much have at least one owner"
  elsif @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was succesfully updated!"
    end
  end


  def destroy
    @project = Project.find(params[:project_id])
    @membership = Membership.find(params[:id])
    @membership.project_id = @project.id
    @membership.destroy
    redirect_to project_memberships_path(@project), alert: "#{@membership.user.full_name} was removed from the project!"
  end


  private
  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
  end

  def set_project
    @project = Project.find(params[:project_id])
    unless @project && @project.users.include?(current_user)
    redirect_to projects_path, alert: 'You do not have access to that project.'
  end
  end

end

app/views/memberships/_form.erb
<% if current_user.project_owner(@project) || current_role == true %>

<div class="well form-inline">
  <%= form_for [@project, @membership] do |f| %>

  <div class="form-group">
    <%= f.collection_select :user_id, User.all, :id, :full_name, {include_blank: "Please select a user..."}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.select(:role, [["Member", :member],["Owner", :owner]], {include_blank: false}, {class:"form-control"}) %>
  </div>
  <%= f.submit 'Add New Member', class:"btn btn-info" %>

  <% end %>
</div>
<% end %>

app/views/memberships/index.html.erb
<div class="page-header">
  <h1><%= @project.name %>: Manage Members</h1>
</div>

<div class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Memberships</li>
</div>

<div class="form-group">
  <%= render partial: "shared/form", locals: {object: @membership} %>
</div>

<%= render 'form' %>

<% if current_user.project_owner(@project) || current_role == true %>
<div class="form-inline">
  <% @project.memberships.each do |membership| %>
  <%= form_for [@project, membership] do |f| %>

  <div class="form-group col-md-2">
    <%= link_to membership.user.full_name, user_path(membership.user) %>
  </div>
  <div class="form-group">
    <%= f.select(:role, [["Member", :member],["Owner", :owner]], {include_blank: false}, {class:"form-control"}) %>

    <%= f.submit "Update", method: :update, class:"btn btn-info" %>
    <% if membership.role == "owner" && @project.memberships.where(role: 1).count == 1 %>
    <span>You are the last owner. </span>
    <% else %>
    <%= link_to '', project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-remove" %>

  <% end %>
</div><br>
  <% end %>
  <% end %>
</div><br>

<% else %>
<table class="table">
  <tbody>
    <% @project.memberships.each do |membership| %>
    <tr>
      <td><%= membership.user.full_name %></td>
      <td><%= membership.role %></td>
      <td>
        <% if membership.user.id == current_user.id || current_role == true%>
        <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden=true></span>'.html_safe, project_membership_path(@project, membership), method: :delete, data: { confirm: "Are you sure you want to delete?"} %>
      </td>
    </tr>


  </tbody>

</table>
<% end %>
<% end %>
<% end %>