config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :tasks
  resources :users

  resources :users
    resources :projects do
      resources :tasks do
        resources :comments
      end
    end

    resources :projects do
      resources :memberships
  end

  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
  get '/signin' => 'authentications#new'
  post '/signin' => 'authentications#create'
  get '/signout' => 'authentications#destroy'

get '/' => 'welcome#index'

get '/faq' => 'common_questions#index'

get '/about' => 'about#index'

get '/terms' => 'terms#index'

get '/tasks' => 'tasks#index'




end

app/models/concerns/task.rb
class Task < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  validates :description, presence: true
  has_many :comments
  has_many :users, through: :comments


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  before_action :set_project

  def index
    @project = Project.find(params[:project_id])
    @comments = Comment.all
    @task = Task.new
    @tasks = Task.all
  end

  def show
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @comments = Comment.all
    @comment = Comment.new
    # @user = User.find(params[:user_id])
  end

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.new(task_params)
    @task.project_id = @project.id
    if @task.save
      redirect_to project_tasks_path(@project), notice: "Task was successfully created!"
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @task.project_id = params[:project_id]
  end

  def update
    @project = Project.find(params[:project_id])
    @task.project_id = params[:project_id]
    if @task.update(task_params)
      redirect_to project_path(@task.project_id), notice: "Task was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task.project_id = params[:project_id]
    @task.destroy
    redirect_to project_tasks_path(@project), alert: "Task was successfully destroyed!"
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
    unless @project && @project.users.include?(current_user)
    redirect_to projects_path, alert: 'You do not have access to that project.'
  end
  end

  def task_params
    params.require(:task).permit(:description, :due, :completed, :project_id)
  end

  def comment_params
    params.require(:comment).permit(:description, :task_id, :user_id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for ([@project, @task]), html: {class:"form-horizontal"} do |f| %>

<%= render partial: "shared/form", locals: {object: @task} %>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :description %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :description, class: "form-control"%>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :due %>
    </div>
    <div class="col-md-4">
      <%= f.date_select :due, class: "form-control"%>
    </div>
  </div>
</div>

<% if @task.description !=nil %>
<div class="form-group">
  <label class="control-label col-md-2">
    Completed
  </label>
        <div class="col-md-4">
          <%= f.check_box(:completed) %>

  </div>
  </div>
<% end %>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class:"btn btn-primary"%>
      <%= link_to 'Cancel', project_tasks_path, class:"btn btn-default" %>
    </div>
  </div>
</div>

<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
<h1>Editing Task</h1>
</div>

<div class="breadcrumb">
  <li><a href="/tasks">Tasks</a></li>
  <li><%= link_to @task.description,  task_path(@task)%></li>
  <li class="active"><%= @task.description %></li>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <div class="pull-right">
  <%=link_to 'New Task', new_project_task_path(@project), :class => "btn btn-info" %>
  </div>
<h1>Tasks for <%=@project.name%></h1>
</div>

<div class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li><a><%= link_to @project.name, project_path(@project)%></a></li>
  <li class="active">Tasks</li>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Due On</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= link_to task.description, project_task_path(@project, task) %> <div class="badge"> <%= Comment.where(:task_id => task.id).count %></div></td>
        <td><%= task.due %></td>
        <td><%= task.completed %></td>
        <td class="text-right">
        <%= link_to 'Edit', edit_project_task_path(@project, task), :class => "btn btn-info" %>
        <%= link_to '', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-remove" %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class="page-header">
<h1>New Task</h1>
</div>

<div class="breadcrumb">
  <li><a href="/tasks">Tasks</a></li>
  <li class="active">New Task</li>
</div>


<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_task_path(@task), :class => "btn btn-info" %>

  </div>
  <h1><%= @task.description %></h1>
</div>


<div class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li><a><%= link_to @project.name, project_path(@project)%></a></li>
  <li><a><%= link_to "Tasks", project_tasks_path(@project, @task)%></a></li>
  <li class="active"><%= @task.description %></li>
</div>

<div>
  <strong>Due On:</strong>
  <%= @task.due %>
</div>


<h3> Comments </h3>


<% @task.comments.each do |comment| %>
<div class="row">
  <div class="col-md-3">
    <% if comment.user == nil %>
    Deleted User
    <% else %>
    <%= link_to User.find(comment.user_id).full_name, user_path(comment.user_id) %>
<% end %>
</div>

<div class="col-md-9">
  <%= comment.description %>
</div>
</div>

<div class="row">
<div class="col-md-3 text-muted">
  <%= time_ago_in_words(comment.created_at)%> ago
</div>
</div>
<br>
<% end %>


<%= form_for [@project, @task, @comment], html: {class:"form-horizontal"} do |f| %>
<div class="form-group">
  <div class="field">
    <div class="col-md-9 col-md-offset-3">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <div class="col-md-9 col-md-offset-3">
      <%= f.submit "Add Comment", class:"btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>