config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :tasks
  resources :users

  resources :users
    resources :projects do
      resources :tasks do
        resources :comments
      end
    end

    resources :projects do
      resources :memberships
  end

  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
  get '/signin' => 'authentications#new'
  post '/signin' => 'authentications#create'
  get '/signout' => 'authentications#destroy'

get '/' => 'welcome#index'

get '/faq' => 'common_questions#index'

get '/about' => 'about#index'

get '/terms' => 'terms#index'

get '/tasks' => 'tasks#index'




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate
  before_action :set_project, only: [:update, :show, :edit, :destroy]
  before_action :check_member, only: [:edit, :destroy]
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
    @membership = Membership.create(project_id: @project.id, user_id: current_user.id, role: 1)
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, alert: 'Project was successfully Destoryed.'
  end


  private

  def set_project
    @project = Project.find(params[:id])
    unless @project && @project.users.include?(current_user)
      redirect_to projects_path, alert: 'You do not have access to that project.'
    end
  end

  def project_params
    params.require(:project).permit(:name)
  end

  def check_member
  @membership = Membership.where(user_id: current_user.id)[0]
  unless @membership.role == 'owner'
    redirect_to projects_path, alert: "You do not have access to that project."
  end
end

end

app/views/projects/_form.html.erb
<%= form_for(@project,  html: {class:"form-horizontal"}) do |f| %>

<%= render partial: "shared/form", locals: {object: @project} %>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :name %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control"%>
    </div>
  </div>
</div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <% if @project.name == nil %>
      <%= f.submit "Create Project", class:"btn btn-primary"%>
      <% else %>
      <%= f.submit "Update Project", class:"btn btn-primary"%>
      <%= link_to 'Cancel', projects_path, class:"btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<div class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li><%= link_to @project.name,  project_path(@project)%></li>
  <li class="active"><%= @project.name %></li>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <a class="btn btn-info" href="/projects/new">New Project</a>
  </div>
  <h1>Projects</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>

  <tbody>
    <% if current_user || current_role == true %>
    <% current_user.projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to pluralize(project.tasks.count, "Task"), project_tasks_path(project, @task)%></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>

<div class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active">New Project</li>
</div>


<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <% if current_user.project_owner(@project) || current_role == true %>
    <%= link_to 'Edit', edit_project_path(@project), :class => "btn btn-info" %>
    <% end %>
  </div>

  <h1><%= @project.name %></h1>
</div>


<div class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active"><%= @project.name %></li>
</div>


<!-- <%= link_to pluralize(@project.tasks.count, "task"), project_tasks_path(@project)  %> -->
<div><%= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project, @task)%></div>
<div><%= link_to pluralize(@project.memberships.count, "Membership"), project_memberships_path(@project, @membership)%></div>

<% if current_user.project_owner(@project) || current_role == true%>
<div class="well">
  <h4> Delete </h4>
  <div> Deleting this project will also delete <%= pluralize(@project.memberships.count, "Membership") %>, <%=  pluralize(@project.tasks.count, "Task") %> and associated comments</div>
<div>  <%= link_to 'Delete', project_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></div>
</div>
<% end %>