config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :tasks
  resources :users

  resources :users
    resources :projects do
      resources :tasks do
        resources :comments
      end
    end

    resources :projects do
      resources :memberships
  end

  get '/signup' => 'registrations#new', as: :signup
  post '/signup' => 'registrations#create'
  get '/signin' => 'authentications#new'
  post '/signin' => 'authentications#create'
  get '/signout' => 'authentications#destroy'

get '/' => 'welcome#index'

get '/faq' => 'common_questions#index'

get '/about' => 'about#index'

get '/terms' => 'terms#index'

get '/tasks' => 'tasks#index'




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Taskly</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Taskly</a>
        <% if current_user || current_role == true %>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% current_user.projects.each do |project| %>
              <li> <%= link_to project.name, project_path(project) %> </li>
              <% end %>
              <li role="presentation" class="divider"></li>
              <li><%= link_to "New Project", new_project_path %></li>
            </ul>
          </li>
          <li ><%= link_to 'Users', users_path %></li>
        </ul>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
        <li><%= link_to current_user.full_name %></li>
        <li><%= link_to 'Sign Out', signout_path %></li>
        <% else %>
        <li><%= link_to 'Sign Up', signup_path %></li>
        <li><%= link_to 'Sign In', signin_path %></li>
        <% end %>
      </ul>

    </div>
  </div>



  <div class="container">
    <% flash.each do |type, message| %>
    <% if type == "notice" %>
    <b>
      <center>
        <div class="alert alert-success">
          <%= message %>
        </div>
      </center>
    </b>
    <% elsif type == "alert" %>
    <b>
      <center>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      </center>
    </b>
    <% end %>
    <% end %>


    <%= yield %>
  </div>
</body>

<div class="container">
  <footer>
    <% if current_user %>


    <div class="row">
      <div class="text-center">
        <a href="/">Home</a>
        |
        <a href="/about">About</a>
        |
        <a href="/terms">Terms</a>
        |
        <a href="/faq">FAQ</a>
      </div>
    </div>
    <% else %>
    <div class="row">
      <div class="col-md-6">
        <a href="/about">About</a>
        |
        <a href="/terms">Terms</a>
        |
        <a href="/faq">FAQ</a>
        |
        <a href="/users">Users</a>
        |
        <a href="/projects">Projects</a>
      </div>

      <div class="col-md-6 text-right">
        <a href="https://www.linkedin.com/in/hayleyblackstock">
          <img alt="LinkedIn" class="img-footer" <%= image_tag('LinkedIn.png') %>
        </a>
        <a href="https://github.com/hayleyblackstock">
          <img alt="Github" class="img-footer" <%= image_tag('GitHub.png') %>
        </a>
        <a href="https://twitter.com/hkblackstock">
          <img alt="Twitter" class="img-footer" <%= image_tag('Twitter.png') %>
        </a>
        <a href="https://students.gschool.it/cohorts/9/students/204">
          <img alt="Galvanize g" class="img-footer" <%= image_tag('gSchool.png') %>
        </a>        </div>
      </div>

      <% end %>
    </footer>
  </div>


  </html>